### PR TITLE
Add german translations

### PR DESCRIPTION
**Pull request by cpiber**
This PR adds German translations

It seems like it's not possible to create translations for an external assembly using ResourceManager, and we need the errors in German.
I noticed this localization was added in #36, if @davideicardi or @jasonhumberstone know how I could provide translations from my project I would also be open to that.

If you ever need updates for the translations feel free to ping me.
I based the translations based on my understanding (mother tongue) and Microsoft's documentation translation.

### CODE REVIEW

**Comment by davideicardi** [comment]
Thank you!
I don't see problems adding translations here.

Can you just check what happen if for some reason one translation is missing? I don't remember the default behavior ...

**Comment by cpiber** [comment]
The default behavior is to fall back to the fallback resource (no language identifier), in this case English

**Review by davideicardi — APPROVED** [review]

**Comment by cpiber** [comment]
Any plans for a new version with the localization included?

**Comment by davideicardi** [comment]
Just released 2.17.1 ! :rocket:

**Pull request merged**
